######################################################################
# Automatically generated by qmake (2.01a) ? 10? 29 00:00:33 2012
######################################################################

TEMPLATE = app
TARGET = malachite-test

QMAKE_CXXFLAGS += -std=c++11

mac {
  QMAKE_LFLAGS_SONAME = -Wl,-install_name,@executable_path/
  QMAKE_CFLAGS_X86_64 = -mmacosx-version-min=10.7
  QMAKE_CXXFLAGS_X86_64 = $$QMAKE_CFLAGS_X86_64
  QMAKE_OBJECTIVE_CFLAGS_X86_64 = $$QMAKE_CFLAGS_X86_64
  QMAKE_LFLAGS_X86_64 = $$QMAKE_CFLAGS_X86_64
}

SOURCES += \
    main.cpp
